export default {
  CHANGE_CARD_VALUE: 'CHANGE_CARD_VALUE',
  CHANGE_CARD_IN_PROGRESS_VALUE: 'CHANGE_CARD_IN_PROGRESS_VALUE',
  CHANGE_LIST_IN_PROGRESS_VALUE: 'CHANGE_LIST_IN_PROGRESS_VALUE',
  CLICK_CARD: 'CLICK_CARD',
  DROP_CARD: 'DROP_CARD',
  HIDE_LIST_IN_PROGRESS: 'HIDE_LIST_IN_PROGRESS',
  SAVE_CARD: 'SAVE_CARD',
  SAVE_LIST: 'SAVE_LIST',
  SHOW_CARD_IN_PROGRESS: 'SHOW_CARD_IN_PROGRESS',
  SHOW_LIST_IN_PROGRESS: 'SHOW_LIST_IN_PROGRESS',
};
