export default {
  ADD_NEW_CARD: 'ADD_NEW_CARD',
  ADD_NEW_LIST: 'ADD_NEW_LIST',
  CHANGE_CARD_VALUE: 'CHANGE_CARD_VALUE',
  CHANGE_NEW_CARD_VALUE: 'CHANGE_NEW_CARD_VALUE',
  CHANGE_NEW_LIST_VALUE: 'CHANGE_NEW_LIST_VALUE',
  CLICK_CARD: 'CLICK_CARD',
  HIDE_NEW_LIST_COMPOSER: 'HIDE_NEW_LIST_COMPOSER',
  MOVE_CARD: 'MOVE_CARD',
  SAVE_NEW_CARD: 'SAVE_NEW_CARD',
  SAVE_NEW_LIST: 'SAVE_NEW_LIST',
};
