export default {
  ADD_NEW_CARD: 'ADD_NEW_CARD',
  CHANGE_CARD_VALUE: 'CHANGE_CARD_VALUE',
  CHANGE_NEW_CARD_VALUE: 'CHANGE_NEW_CARD_VALUE',
  CLICK_CARD: 'CLICK_CARD',
  SAVE_NEW_CARD: 'SAVE_NEW_CARD'
}
